language: python
cache: pip

before_script:
  - pip install tox

script: tox

matrix:
  include:

    - python: "3.9"
      env: TOXENV=py36

    - python: "3.10"
      env: TOXENV=py37

    - python: "3.9"
      env: TOXENV=linting

notifications:
  email: false
